version: '2'
services:
  app:
    container_name: app
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/home/solidus
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=secret
      - DB=postgresql://solidus:solidus@db:5432/solidus2?pool=30
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=solidus
      - POSTGRES_PASSWORD=solidus
      - POSTGRES_USER=solidus
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: 
